temporarily disable active_chatters list
It looks like we need to properly protect active_chatters list from
concurrent accesses to prevent this from happening:

  RuntimeError: dictionary changed size during iteration

In the meantime simply disable the actice_chatters list and rely purely
on the list of users provided by bot.get_chatters(), so we can prevent
the game from crashing.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>